export {
    default as Input,
    default as InputType
} from './input.components/input.component'
export { default as EmailInput } from './input.components/user/email-user-input.component'
export { default as PasswordInput } from './input.components/user/password-user-input.component'
export { default as UsernameInput } from './input.components/user/username-user-input.component'
export { default as AgeInput } from './input.components/user/age-user-input.component'
export { default as TelephoneInput } from './input.components/user/telephone-user-input.component'
export { default as DniInput } from './input.components/user/dni-user-input.component'
export { default as LastnameInput } from './input.components/user/lastname-user-input.component'
export { default as RepeatPasswordInput } from './input.components/user/repeat-password-user-input.component'
export { default as Select } from './input.components/select.component'
export { default as PetAgeInput } from './input.components/pet/age-pet-input.component'
export { default as PetNameInput } from './input.components/pet/name-pet-input.component'
export { default as PetRaceInput } from './input.components/pet/race-pet-input.component'
export { default as PetOriginInput } from './input.components/pet/origin-pet-input.component'
export { default as PetColorInput } from './input.components/pet/color-pet-input.component'
export { default as PetCaracteristicsInput } from './input.components/pet/caracteristics-pet-input.component'
export { default as PetSexInput } from './input.components/pet/sex-pet-input.component'
export { default as PetSizeInput } from './input.components/pet/size-pet-input.component'
export { default as PetWeightInput } from './input.components/pet/weight-pet-input.component'